content:
  - name: twin_data
    label: Twin Profili
    type: file
    path: twin.json
    fields:
      - name: profilePhoto
        label: Profil Fotoğrafı URL
        type: string
      - name: modalPhoto
        label: Modal Fotoğrafı URL
        type: string
      - name: miniIcons
        label: Mini İkonlar
        type: list
        fields:
          - name: platform
            label: Platform
            type: string
          - name: url
            label: URL (Link)
            type: string
          - name: cssClass
            label: CSS Sınıfı
            type: string
          - name: icon
            label: İkon URL
            type: string
      - name: links
        label: Bağlantılar
        type: list
        fields:
          - name: platform
            label: Platform
            type: string
          - name: username
            label: Kullanıcı Adı
            type: string
          - name: url
            label: URL (Link)
            type: string
          - name: bg
            label: Arka Plan Resmi URL
            type: string

  - name: kazikate_data
    label: Kazikate Profili
    type: file
    path: kazikate.json
    fields:
      - name: profilePhoto
        label: Profil Fotoğrafı URL
        type: string
      - name: modalPhoto
        label: Modal Fotoğrafı URL
        type: string
      - name: miniIcons
        label: Mini İkonlar
        type: list
        fields:
          - name: platform
            label: Platform
            type: string
          - name: url
            label: URL (Link)
            type: string
          - name: cssClass
            label: CSS Sınıfı
            type: string
          - name: icon
            label: İkon URL
            type: string
      - name: links
        label: Bağlantılar
        type: list
        fields:
          - name: platform
            label: Platform
            type: string
          - name: username
            label: Kullanıcı Adı
            type: string
          - name: url
            label: URL (Link)
            type: string
          - name: bg
            label: Arka Plan Resmi URL
            type: string

  - name: music_data
    label: Müzik Listesi
    type: file
    path: music.json
    fields:
      - name: playlist
        label: Şarkılar (Playlist)
        type: list
        fields:
          - name: title
            label: Şarkı Adı
            type: string
          - name: artist
            label: Sanatçı
            type: string
          - name: file
            label: Şarkı Dosyası (URL)
            type: string
